version: '3.8'

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "81:81"  # Web GUI access on port 81
    environment:
      # Set environment variables for database password and other settings
      - DB_SQLITE_FILE=/data/database.sqlite  # SQLite database file path (for simplicity)
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}   # Root MySQL password
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}           # User MySQL password
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
